### ISSUE TITLE
Static IR Image Processing

### ISSUE THREAD

**Issue by chenchen2015** [chenchen2015/CameraTrackingSystem#1]
Use OpenCV to process IR filtered images in the Data folder. Assigned to @nbshenxm and

**Comment by nbshenxm** [comment]
- [ ] Encountered bugs when trying to process all images in a folder using a loop: Exception at memory location 0x0000007633F5B5A0

**Comment by shitij23** [comment]
Description

Image processing algorithm should automatically read through all the images stored within the folder

TODO

- [ ] Write method to automatically read or loop through all images in the folder
