### ISSUE TITLE
Research on Machine Learning Algorithm

### ISSUE THREAD

**Issue by chenchen2015** [chenchen2015/CameraTrackingSystem#11]
**Description**
Can we train a machine learning algorithm that takes all the labeled gantry samples (gantry coordinates + *N* images, *N* is the number of cameras that we are using) to predict the gantry coordinates of new images we are taking? If so, what structure and algorithm works the best?

**Comment by shitij23** [comment]
Reading white papers on Machine Learning algorithms. Presentation due - 4/24
