### ISSUE TITLE
Automated Data Acquisition Test

### ISSUE THREAD

**Issue by chenchen2015** [chenchen2015/CameraTrackingSystem#12]
**Description**
Now that we have both #10 and #5 done, our next step is to test data acquisition process, which involves:

1. You need to make both Gantry API and XCAP API function calls **inside MATLAB** in order to have synchronous image capture.
2. Use Gantry API to move SensorPod to each discrete sample positions and hold the position in order for the camera to capture. Store raw gantry coordinates.
3. Use XCAP API to capture images while the gantry is waiting. There are some techniques you can consider to improve image quality.
   - Capture N images each camera and use the average or median image as the output.
   - Wait for a brief time before you start the capture. This should help you make sure the gantry has stopped moving.
4. Store captured images and the corresponding gantry coordinates as a sample pair.
5. Repeat step 2 until finished.

**Task List**
- [x] **Two point test** - Write a MATLAB script that moves the gantry from point A to B and use XCAP API to capture two sets of images. Manually check if your script captured the correct image and the gantry coordinates is associated with the right image.
- [x] Expand the script you wrote. Add an adaptive sampling subroutine that automatically generates N gantry points to sample within the entire gantry workspace, where N will be specified as a parameter. Add a delay function between every gantry movement. Test your program.

**Comment by nbshenxm** [comment]
Issue: how to name the collected images so that the old ones won't get replaced by the new ones?
Possible solutions:
(1) add image collecting time&date

**Comment by chenchen2015** [comment]
Timestamp definitely sounds like a good solution. 

Or you can try to something like **Camera-2-Session-1-Sample-001-Seq-0001.png**, which has the following parameters:
- **Camera ID** - ID of the camera
- **Session ID** - ID of this data session.
- **Sample ID** - ID of current position sample. Say if you are going to sample 5 different positions, your sample ID can be from 001~005
- **Sequence ID** - When you are capturing multiple images at each position (to make sure image quality is good), use this to label the ID of each image.

**Comment by nbshenxm** [comment]
A working version of automatic data collecting program is uploaded. Each image has a filename in format of "DD-MM-YYYY HH-MM-SS_Unit#_Seq$$$$.bmp".
