### ISSUE TITLE
Realtime IR Image Processing

### ISSUE THREAD

**Issue by chenchen2015** [chenchen2015/CameraTrackingSystem#2]
Write image processing algorithm in MATLAB to process the collected images and output the coordinates.

- [x] detect the LED lights
- [ ] output nx3x2 matrix

Assigned to @nbshenxm and

**Comment by chenchen2015** [comment]
how's the progress so far? @nbshenxm

**Comment by nbshenxm** [comment]
I tried the trackLEDs program in repository. It worked well, but requires  input the image pairs and name the output file manually. I'm trying to modify the program to do those automatically.

**Comment by nbshenxm** [comment]
The image processing algorithm is modified to run automatically. It works well for normal images, but have trouble with empty images. I will work on dealing with empty image exceptions.
