### ISSUE TITLE
Exception Handling - Empty Images

### ISSUE THREAD

**Issue by shitij23** [chenchen2015/CameraTrackingSystem#8]
**Description**
Currently no exception is in place for images with no view of the Gantry. 

**TODO**

- [ ] Include method to skip through image with no detected gantry/LED coordinates

**Comment by shitij23** [comment]
- on hold

**Comment by chenchen2015** [comment]
@nbshenxm will keep working on this

**Comment by nbshenxm** [comment]
I will deal with it while modifying the LED tracking program

**Comment by nbshenxm** [comment]
Done. When the image processing algorithm encounters an empty image, it returns an empty array.
